version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: src/User.Api/Dockerfile
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      ConnectionStrings__UsersDb: Host=db;Port=5432;Database=postgres;Username=postgres;Password=postgres;
      Serilog__MinimumLevel__Default: Verbose
      Serilog__MinimumLevel__Override__Microsoft: Verbose
      Pagination__BaseUrl: http://localhost:5000
    depends_on:
      - db
    networks:
      - elk
  db:
    image: postgres:13
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    networks:
      - elk
networks:
  elk:
    driver: bridge